/*
 * Automatically generated by jrpcgen 1.0.7 on 25.01.10 18:14
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package daqcore.oncrpc.vxi11core;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Device_Link implements XdrAble, java.io.Serializable {

    public int value;

    private static final long serialVersionUID = -7675062279205579624L;

    public Device_Link() {
    }

    public Device_Link(int value) {
        this.value = value;
    }

    public Device_Link(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(value);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        value = xdr.xdrDecodeInt();
    }

}
// End of Device_Link.java
