/*
 * Automatically generated by jrpcgen 1.0.7 on 25.01.10 18:14
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package daqcore.oncrpc.vxi11core;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Device_DocmdResp implements XdrAble, java.io.Serializable {
    public Device_ErrorCode error;
    public byte [] data_out;

    private static final long serialVersionUID = 2763288170958409925L;

    public Device_DocmdResp() {
    }

    public Device_DocmdResp(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        error.xdrEncode(xdr);
        xdr.xdrEncodeDynamicOpaque(data_out);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        error = new Device_ErrorCode(xdr);
        data_out = xdr.xdrDecodeDynamicOpaque();
    }

}
// End of Device_DocmdResp.java
