/*
 * Automatically generated by jrpcgen 1.0.7 on 25.01.10 18:14
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package daqcore.oncrpc.vxi11core;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Device_GenericParms implements XdrAble, java.io.Serializable {
    public Device_Link lid;
    public Device_Flags flags;
    public int lock_timeout;
    public int io_timeout;

    private static final long serialVersionUID = -3799584945358787987L;

    public Device_GenericParms() {
    }

    public Device_GenericParms(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        lid.xdrEncode(xdr);
        flags.xdrEncode(xdr);
        xdr.xdrEncodeInt(lock_timeout);
        xdr.xdrEncodeInt(io_timeout);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        lid = new Device_Link(xdr);
        flags = new Device_Flags(xdr);
        lock_timeout = xdr.xdrDecodeInt();
        io_timeout = xdr.xdrDecodeInt();
    }

}
// End of Device_GenericParms.java
