/*
 * Automatically generated by jrpcgen 1.0.7 on 22.12.09 14:59
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.daqcore.oncrpc.vxi11core;
/**
 * Enumeration (collection of constants).
 */
public interface Device_AddrFamily {

    public static final int DEVICE_TCP = 0;
    public static final int DEVICE_UDP = 0+1;

}
// End of Device_AddrFamily.java
