/*
 * Automatically generated by jrpcgen 1.0.7 on 22.12.09 14:59
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package org.daqcore.oncrpc.vxi11core;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Device_EnableSrqParms implements XdrAble, java.io.Serializable {
    public Device_Link lid;
    public boolean enable;
    public byte [] handle;

    private static final long serialVersionUID = -5513193212718078713L;

    public Device_EnableSrqParms() {
    }

    public Device_EnableSrqParms(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        lid.xdrEncode(xdr);
        xdr.xdrEncodeBoolean(enable);
        xdr.xdrEncodeDynamicOpaque(handle);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        lid = new Device_Link(xdr);
        enable = xdr.xdrDecodeBoolean();
        handle = xdr.xdrDecodeDynamicOpaque();
    }

}
// End of Device_EnableSrqParms.java
