/*
 * Automatically generated by jrpcgen 1.0.7 on 19.05.11 01:50
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package daqcore.io.oncrpc.vxi11core;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class Device_ReadParms implements XdrAble, java.io.Serializable {
    public Device_Link lid;
    public int requestSize;
    public int io_timeout;
    public int lock_timeout;
    public Device_Flags flags;
    public byte termChar;

    private static final long serialVersionUID = 2161617317113605929L;

    public Device_ReadParms() {
    }

    public Device_ReadParms(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        lid.xdrEncode(xdr);
        xdr.xdrEncodeInt(requestSize);
        xdr.xdrEncodeInt(io_timeout);
        xdr.xdrEncodeInt(lock_timeout);
        flags.xdrEncode(xdr);
        xdr.xdrEncodeByte(termChar);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        lid = new Device_Link(xdr);
        requestSize = xdr.xdrDecodeInt();
        io_timeout = xdr.xdrDecodeInt();
        lock_timeout = xdr.xdrDecodeInt();
        flags = new Device_Flags(xdr);
        termChar = xdr.xdrDecodeByte();
    }

}
// End of Device_ReadParms.java
